SELECT
    'JE'                            AS JOURNAL,
    ACCT.GLACCTID                   AS GLACCTID,
    ACCT.GLACCOUNTACCTNAME          AS GLACCOUNTACCTNAME,
    ACCT.GLACCOUNTNICKNAME          AS GLACCOUNTNICKNAME,
    ACCT.GLACCOUNTSTATUS            AS GLACCOUNTSTATUS,
    ACCT.GLACCOUNTCATEGORY          AS GLACCOUNTCATEGORY,
    ENTRY.GJEntryDate               AS ENTRYDATE,
    


    /* DEBIT AMOUNT */
    CASE
        WHEN ALLOC.GJAllocationAmount > 0
            THEN ALLOC.GJAllocationAmount
        ELSE 0
    END AS DEBITAMOUNT,

    /* CREDIT AMOUNT */
    CASE
        WHEN ALLOC.GJAllocationAmount < 0
            THEN ALLOC.GJAllocationAmount
        ELSE 0
    END AS CREDITAMOUNT,
    ENTRY.GJEntryExpl                as EXPLANATION

FROM PCLAW_GJENTRY ENTRY
JOIN PCLAW_GJALLOC ALLOC 
    ON ENTRY.GJENTRYID = ALLOC.GJALLOCATIONGJID
JOIN PCLAW_GLACCT ACCT
    ON ALLOC.GJALLOCATIONGJID = ACCT.GLACCTID
JOIN PCLAW_TRANIDX TRAN
    ON ENTRY.GJENTRYID = TRAN.TRANINDEXSEQUENCEID

WHERE TRAN.TRANINDEXSTATUS = 0;